name: PR Labeler
on: [ pull_request_target ]

permissions:
  # All other permissions are set to none
  checks: write
  contents: read
  pull-requests: write
  
jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
