name: Pull Request Automerge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

jobs:
  merge_dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull request
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "dependencies"
          MERGE_FILTER_AUTHOR: "dependabot"
          LOG: "TRACE"
          MERGE_METHOD: "squash"
