name: Pull Request Automerge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  workflow_dispatch:
    inputs:
      manual_run:
        description: 'Run the workflow for all pull requests'
        default: false
        required: false

jobs:
  merge_dependabot:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.inputs.manual_run == 'true' }} || (
        github.event_name == 'pull_request' &&
        github.event.action != 'closed' &&
        contains(github.event.pull_request.labels.*.name, 'dependencies') &&
        github.event.pull_request.user.login == 'dependabot[bot]' &&
        github.event.pull_request.number == github.event.pull_request.number
      )
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "dependencies"
          MERGE_FILTER_AUTHOR: "dependabot"
          LOG: "TRACE"
          MERGE_METHOD: "squash"
        with:
          pull-request-number: ${{ github.event.pull_request.number }}

      - name: feedback
        if: ${{steps.automerge.outputs.mergeResult == 'merged'}}
        run: |
          echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} merged!"
