name: Pull Request Automerge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  check_suite:
    types:
      - completed
  status: {}

jobs:
  merge_dependabot:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "dependencies"
          MERGE_FILTER_AUTHOR: "dependabot"
          LOG: "TRACE"
          MERGE_METHOD: "squash"
      - run: "echo ${{steps.automerge.outputs }}"

      - name: feedback
        if: steps.automerge.outputs.mergeResult == "merged"
        run: |
          echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} merged!"
