name: Pull Request Rules

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

jobs:
  merge_dependabot:
    runs-on: ubuntu-latest
    if: |
      github.event.label.name == 'dependencies' &&
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      github.event.pull_request.commits >= 1 &&
      contains(github.event.pull_request.labels.*.name, 'dependencies')
    steps:
      - run: |
          echo "pull_request : ${{ github.event.pull_request }}"
          echo "pull_request : ${{ github.event.pull_request.labels.*.name }}"
      - name: Merge pull request
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
